version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: gestion-pdagogique-laravel-last-mysql-1
    environment:
      MYSQL_DATABASE: projet_Scolaire
      MYSQL_USER: ibrahima
      MYSQL_PASSWORD: Sonatel@2024
      MYSQL_ROOT_PASSWORD: Sonatel@2024  # Optionnel
    ports:
      - "3307:3306"  # Port hôte pour accéder à MySQL
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:S2DOPPcAmWjqZCxZEtkPiabEUOh1LM8W22X9m9iHMhA=
      APP_DEBUG: true
      APP_URL: http://localhost:9000  # Correspond au port Nginx
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306  # Utiliser 3306 pour la connexion au conteneur MySQL
      DB_DATABASE: projet_Scolaire
      DB_USERNAME: ibrahima
      DB_PASSWORD: Sonatel@2024
      BROADCAST_CONNECTION: log
      CACHE_DRIVER: array
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      AUTH_SERVICE: passport
    depends_on:
      - mysql  # Assurez-vous que MySQL est prêt avant de démarrer l'application

  webserver:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
